### ISSUE TITLE
Extend build system

### ISSUE THREAD

**Issue by Kirill71** [hrandib/pc_fancontrol#1]
I think it's a great idea to add the possibility of using Cmake as an alternative build system. Plenty of IDEs support it,  whereas only the Qt creator supports QBS.

**Comment by Kirill71** [comment]
@hrandib Pls, assign this issue to me

**Comment by hrandib** [comment]
Agree, it would be nice to have such possibility

**Comment by Kirill71** [comment]
A new pull request has been created

**Comment by hrandib** [comment]
Merged. Using subject tags to automatically close issue is a better approach
