### ISSUE TITLE
Add support for `drivetemp` hwmon driver

### ISSUE THREAD

**Issue by mafredri** [hrandib/pc_fancontrol#6]
Would it be possible to add support for the `drivetemp` hwmon driver (`modprobe drivetemp`)?

Since `pc_fancontrol` currently detects hwmons via `name`, it's not possible to use `drivetemp` for HDD temperature monitoring. All instances of `drivetemp` hwmons are named `drivetemp` and this causes `pc_fancontrol` to only pick one.

Example:

```shell
# for m in /sys/class/hwmon/*; do echo $m: $(<$m/name); done
/sys/class/hwmon/hwmon0: acpitz
/sys/class/hwmon/hwmon1: it8728
/sys/class/hwmon/hwmon2: drivetemp
/sys/class/hwmon/hwmon3: drivetemp
/sys/class/hwmon/hwmon4: drivetemp
/sys/class/hwmon/hwmon5: drivetemp
/sys/class/hwmon/hwmon6: coretemp
```

And accompanying `pc_fancontrol` output:

```
Jul 10 14:00:08 pc_fancontrol[3730597]: Version: 1.2.0
Jul 10 14:00:08 pc_fancontrol[3730597]: coretemp: "/sys/class/hwmon/hwmon6"
Jul 10 14:00:08 pc_fancontrol[3730597]: coretemp init success
Jul 10 14:00:08 pc_fancontrol[3730597]: it8728: "/sys/class/hwmon/hwmon1"
Jul 10 14:00:08 pc_fancontrol[3730597]: it8728 init success
Jul 10 14:00:08 pc_fancontrol[3730597]: drivetemp: "/sys/class/hwmon/hwmon4"
Jul 10 14:00:08 pc_fancontrol[3730597]: drivetemp init success
```

The `sensors` command outputs a more detailed name, like `drivetemp-scsi-0-0`. For this case, it could be mimicked by detecting that `/sys/class/hwmon/hwmon2/device/subsystem` is `bus/scsi` and that `/sys/class/hwmon/hwmon2/device` links to `0:0:0:0` (hence `scsi-0-0`). There is probably a better way to do this though, as this wouldn't work for the it87 driver which is named as `it8728-isa-0290` by `sensors`.

My current workaround is to use `shell_cmd`, but I'd prefer to be able to uncomment the lines above:

```yaml
sensors:
  - hdd35_1:
      # type: drivetemp-scsi-0-0
      # bind: temp1
      type: shell_cmd
      bind: "hddtemp --numeric SATA:/dev/disk/by-path/pci-0000:00:13.0-ata-1.0"
```

PS. I've been using `pc_fancontrol` for a while and it's simply awesome, big thanks for creating this project!

**Comment by hrandib** [comment]
Hi, @mafredri!
I totally missed 'drivetemp' and I liked it.
Can't promise, but I also interested in this feature.
Though I have a concern regarding the side of a fix. It looks like a workaround, 
maybe we need to consider to extend drivetemp itself to properly name the nodes.
Is it the [origin](https://github.com/groeck/drivetemp) ?

**Comment by hrandib** [comment]
The second surprise is that the 'drivetemp' module is already available in the kernel. So nothing to do with it.
I'll think about how better to add this functionality

**Comment by hrandib** [comment]
Works for me but some feedback would be good

**Comment by mafredri** [comment]
Thanks for working on this @hrandib, I like your solution! I gave it a spin and it works as promised. The only thing missing for me still is being able to bind to SCSI device path. If I understand `device/wwid` correctly, this value would change if a drive is replaced? The reason I'd like to use the SCSI path is that it'll always stay the same.

One way to achieve this would be to extend your solution with the ability to detect the presence of a file/folder:

```
❯ ls /sys/class/hwmon/*/device/scsi_device/
/sys/class/hwmon/hwmon1/device/scsi_device/:
0:0:0:0/

/sys/class/hwmon/hwmon2/device/scsi_device/:
1:0:0:0/

/sys/class/hwmon/hwmon3/device/scsi_device/:
4:0:0:0/

/sys/class/hwmon/hwmon4/device/scsi_device/:
5:0:0:0/
```

For example, if `device/scsi_device/1:0:0:0` exists, then bind.

**Comment by hrandib** [comment]
@mafredri please check

**Comment by mafredri** [comment]
Works great @hrandib, thanks!
