### ISSUE TITLE
No longer builds on Debian (Bullseye)

### ISSUE THREAD

**Issue by mafredri** [hrandib/pc_fancontrol#7]
Hey,

I just wanted to let you know that the project no longer builds on Debian (Bullseye).

```
/home/maf/src/pc_fancontrol/src/controller.cpp:26:10: fatal error: syncstream: No such file or directory
   26 | #include <syncstream>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/pc_fancontrol.dir/build.make:108: src/CMakeFiles/pc_fancontrol.dir/controller.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: src/CMakeFiles/pc_fancontrol.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

My `g++ --version` is: `g++ (Debian 10.2.1-6) 10.2.1 20210110`

It looks like a new(er) C++ feature that may not be supported. Are there any workarounds?

**Comment by hrandib** [comment]
You need to use gcc 11, install it separately. Bullseye doesn't have required support of C++20 in libraries

**Comment by mafredri** [comment]
I want to avoid installing too many unsupported (by Bullseye) libraries, especially large ones like gcc/libstdc++. I can build it in Docker (e.g. official `gcc:11-bullseye` image), but there'd still be the problem of missing/incompatible `libstdc++`.

I tried to `make CXXFLAGS=-static-libstdc++` but that didn't seem to do anything. I don't care about binary size, just convenience/effort.

**Comment by hrandib** [comment]
Clear. Conditional compilation for gcc10 would resolve this issue. Syncstream could be replaced by cout, only logs consistency is impacted in rare cases.

**Comment by hrandib** [comment]
@mafredri Please compile and run, not checked in runtime by me

**Comment by mafredri** [comment]
That's awesome @hrandib, I really appreciate you adding support for gcc10, I know it adds a maintenance burden, so thank you!

For some reason I needed to add a few includes (#8), but otherwise it's working great!

**Comment by hrandib** [comment]
You're welcome)
